"""
Export formatters for Wikipedia articles in various formats.
"""
import markdown
from jinja2 import Template
from typing import Dict, Optional

# Make weasyprint optional for systems without required dependencies
try:
    from weasyprint import HTML
    WEASYPRINT_AVAILABLE = True
except (ImportError, OSError):
    WEASYPRINT_AVAILABLE = False


class ExportFormatter:
    """Format and export Wikipedia articles to different formats."""

    @staticmethod
    def to_markdown(
        article: str,
        title: str,
        infobox: Optional[str] = None,
        summary: Optional[str] = None
    ) -> str:
        """
        Convert article to Markdown format.

        Args:
            article: The article content.
            title: Article title.
            infobox: Optional infobox content.
            summary: Optional summary.

        Returns:
            Markdown formatted string.
        """
        md_content = f"# {title}\n\n"
        
        if summary:
            md_content += f"> **Summary:** {summary}\n\n"
        
        if infobox:
            md_content += "## Infobox\n\n"
            md_content += f"```\n{infobox}\n```\n\n"
        
        md_content += "## Article\n\n"
        md_content += article
        md_content += "\n\n---\n"
        md_content += f"*Generated by Oman Wikipedia Generator*\n"
        
        return md_content

    @staticmethod
    def to_html(
        article: str,
        title: str,
        infobox: Optional[str] = None,
        summary: Optional[str] = None,
        style: str = "wikipedia"
    ) -> str:
        """
        Convert article to HTML format.

        Args:
            article: The article content.
            title: Article title.
            infobox: Optional infobox content.
            summary: Optional summary.
            style: CSS style theme (wikipedia, modern, minimal).

        Returns:
            HTML formatted string.
        """
        # Convert markdown to HTML
        article_html = markdown.markdown(article, extensions=['extra', 'codehilite'])
        
        # Get CSS based on style
        css = ExportFormatter._get_css(style)
        
        # Create HTML template
        template = Template("""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <style>
        {{ css }}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>{{ title }}</h1>
        </header>
        
        {% if summary %}
        <div class="summary">
            <strong>Summary:</strong> {{ summary }}
        </div>
        {% endif %}
        
        <div class="content-wrapper">
            {% if infobox %}
            <aside class="infobox">
                <h3>Quick Facts</h3>
                <pre>{{ infobox }}</pre>
            </aside>
            {% endif %}
            
            <article class="main-content">
                {{ article_html | safe }}
            </article>
        </div>
        
        <footer>
            <p><em>Generated by Oman Wikipedia Generator</em></p>
        </footer>
    </div>
</body>
</html>
        """)
        
        return template.render(
            title=title,
            article_html=article_html,
            infobox=infobox,
            summary=summary,
            css=css
        )

    @staticmethod
    def to_pdf(
        article: str,
        title: str,
        output_path: str,
        infobox: Optional[str] = None,
        summary: Optional[str] = None
    ) -> str:
        """
        Convert article to PDF format.

        Args:
            article: The article content.
            title: Article title.
            output_path: Path to save the PDF file.
            infobox: Optional infobox content.
            summary: Optional summary.

        Returns:
            Path to the generated PDF file.
        """
        if not WEASYPRINT_AVAILABLE:
            raise RuntimeError(
                "PDF export requires WeasyPrint and its dependencies. "
                "On Windows, you'll need to install GTK3. "
                "See: https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#windows "
                "Alternatively, use Docker to run the application with all dependencies."
            )
        
        # First convert to HTML
        html_content = ExportFormatter.to_html(article, title, infobox, summary, style="minimal")
        
        # Convert HTML to PDF using WeasyPrint
        HTML(string=html_content).write_pdf(output_path)
        
        return output_path

    @staticmethod
    def _get_css(style: str) -> str:
        """Get CSS styling based on theme."""
        
        wikipedia_css = """
        body {
            font-family: 'Georgia', 'Times New Roman', serif;
            line-height: 1.6;
            color: #222;
            background-color: #f8f9fa;
            margin: 0;
            padding: 20px;
        }
        .container {
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            padding: 40px;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }
        header h1 {
            font-size: 2.5em;
            border-bottom: 1px solid #a2a9b1;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }
        .summary {
            background: #f8f9fa;
            border-left: 4px solid #0645ad;
            padding: 15px;
            margin: 20px 0;
            font-style: italic;
        }
        .content-wrapper {
            display: flex;
            gap: 30px;
        }
        .infobox {
            flex: 0 0 300px;
            background: #f8f9fa;
            border: 1px solid #a2a9b1;
            padding: 20px;
            font-size: 0.9em;
        }
        .infobox h3 {
            margin-top: 0;
            text-align: center;
            font-size: 1.2em;
        }
        .infobox pre {
            white-space: pre-wrap;
            font-family: inherit;
        }
        .main-content {
            flex: 1;
        }
        .main-content h2 {
            font-size: 1.8em;
            border-bottom: 1px solid #a2a9b1;
            margin-top: 30px;
        }
        .main-content h3 {
            font-size: 1.4em;
            margin-top: 20px;
        }
        footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #a2a9b1;
            text-align: center;
            color: #72777d;
        }
        """
        
        modern_css = """
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            line-height: 1.8;
            color: #333;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            margin: 0;
            padding: 40px 20px;
        }
        .container {
            max-width: 1000px;
            margin: 0 auto;
            background: white;
            padding: 60px;
            border-radius: 15px;
            box-shadow: 0 20px 60px rgba(0,0,0,0.3);
        }
        header h1 {
            font-size: 3em;
            color: #667eea;
            margin-bottom: 30px;
            font-weight: 700;
        }
        .summary {
            background: linear-gradient(to right, #f093fb 0%, #f5576c 100%);
            color: white;
            padding: 20px 25px;
            border-radius: 10px;
            margin: 30px 0;
        }
        .content-wrapper {
            display: flex;
            gap: 40px;
            margin-top: 40px;
        }
        .infobox {
            flex: 0 0 320px;
            background: #f8f9fa;
            border-radius: 10px;
            padding: 25px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }
        .infobox h3 {
            color: #667eea;
            margin-top: 0;
        }
        .main-content {
            flex: 1;
        }
        .main-content h2 {
            color: #764ba2;
            font-size: 2em;
            margin-top: 40px;
        }
        footer {
            margin-top: 60px;
            padding-top: 30px;
            text-align: center;
            color: #999;
            font-size: 0.9em;
        }
        """
        
        minimal_css = """
        body {
            font-family: 'Helvetica Neue', Arial, sans-serif;
            line-height: 1.7;
            color: #000;
            background: white;
            margin: 0;
            padding: 20px;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 40px;
        }
        header h1 {
            font-size: 2.2em;
            font-weight: 300;
            margin-bottom: 20px;
        }
        .summary {
            border-left: 3px solid #000;
            padding-left: 20px;
            margin: 30px 0;
            font-style: italic;
        }
        .content-wrapper {
            margin-top: 40px;
        }
        .infobox {
            background: #fafafa;
            padding: 20px;
            margin-bottom: 30px;
            border: 1px solid #eee;
        }
        .main-content h2 {
            font-size: 1.6em;
            font-weight: 400;
            margin-top: 40px;
            margin-bottom: 15px;
        }
        footer {
            margin-top: 60px;
            text-align: center;
            font-size: 0.85em;
            color: #666;
        }
        """
        
        styles = {
            "wikipedia": wikipedia_css,
            "modern": modern_css,
            "minimal": minimal_css
        }
        
        return styles.get(style, wikipedia_css)


class BatchExporter:
    """Export multiple articles in batch."""

    @staticmethod
    def export_batch(
        articles: Dict[str, str],
        format: str,
        output_dir: str,
        **kwargs
    ) -> Dict[str, str]:
        """
        Export multiple articles to specified format.

        Args:
            articles: Dictionary mapping titles to article content.
            format: Output format (markdown, html, pdf).
            output_dir: Directory to save exported files.
            **kwargs: Additional arguments for formatters.

        Returns:
            Dictionary mapping titles to output file paths.
        """
        import os
        
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)
        
        results = {}
        
        for title, content in articles.items():
            # Sanitize filename
            safe_filename = "".join(c for c in title if c.isalnum() or c in (' ', '-', '_')).rstrip()
            safe_filename = safe_filename.replace(' ', '_')
            
            if format == "markdown":
                filepath = os.path.join(output_dir, f"{safe_filename}.md")
                md_content = ExportFormatter.to_markdown(content, title, **kwargs)
                with open(filepath, 'w', encoding='utf-8') as f:
                    f.write(md_content)
                results[title] = filepath
            
            elif format == "html":
                filepath = os.path.join(output_dir, f"{safe_filename}.html")
                html_content = ExportFormatter.to_html(content, title, **kwargs)
                with open(filepath, 'w', encoding='utf-8') as f:
                    f.write(html_content)
                results[title] = filepath
            
            elif format == "pdf":
                filepath = os.path.join(output_dir, f"{safe_filename}.pdf")
                ExportFormatter.to_pdf(content, title, filepath, **kwargs)
                results[title] = filepath
            
            else:
                raise ValueError(f"Unsupported format: {format}")
        
        return results
